services:

## -- Encoders -- ##
    yan.encoder.json_field:
        class: Site\UtilityBundle\Encoder\JsonFieldEncoder

    yan.encoder.twitter_handler:
        class: Site\UtilityBundle\Encoder\TwitterHandlerEncoder

## -- Twig Extensions -- ##
    yan.twig.extension.english:
        class: Site\UtilityBundle\Twig\Extension\EnglishGrammarExtension
        tags:
            - { name: twig.extension }